# font_family IosevkaTerm Nerd Font
font_size 12.0
background_opacity 1.0
dynamic_background_opacity yes
# background #000000
# background_blur 0

window_margin_width 3
window_padding_width 20
single_window_margin_width 0
window_border_width 1pt
# active_border_color #44ffff
enable_audio_bell no
shell_integration enabled
enabled_layouts tall

tab_bar_style powerline

scrollback_lines 10000
scrollback_pager nvim +Man!
notify_on_cmd_finish unfocused 5
allow_remote_control yes
listen_on unix:/tmp/mykitty

cursor_trail 3

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down
map ctrl+shift+a>m set_background_opacity +0.1 
map ctrl+shift+a>l set_background_opacity -0.1 

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="VictorMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
