color0 #121315
color1 #ffb4ab
color2 #aacae7
color3 #bcc8d4
color4 #dfbbe1
color5 #aacae7
color6 #bcc8d4
color7 #e3e2e4
color8 #8c9197
color9 #ffb4ab
color10 #aacae7
color11 #bcc8d4
color12 #dfbbe1
color13 #aacae7
color14 #bcc8d4
color15 #e3e2e4

cursor                #e3e2e4
cursor_text_color     #121315
background            #121315
foreground            #e3e2e4
selection_foreground  #c2c7cd
selection_background  #42474d
active_border_color   #aacae7
inactive_border_color #42474d
url_color             #aacae7

active_tab_foreground   #10334a
active_tab_background   #aacae7
inactive_tab_foreground #c2c7cd
inactive_tab_background #42474d
cursor_trail_color      #c2c7cd
